### PR TITLE
feat: improve window preview shape

### PR DESCRIPTION
**Pull request by ShlomoCode**
Continuation of https://github.com/ejbills/DockDoor/pull/87

Since not all apps have the same level of window corner rounding, we simply set a transparent background, and display the window as it is instead of interfering with its shape. In addition, we define the gradient overlay with a mask so that it does not color the transparent corners as well.

There is duplication here in defining the gradient but I haven't found a nice way to avoid it. I would love to learn!

### CODE REVIEW

**Comment by ejbills** [comment]
I renamed a commit based on your feedback and force pushed, seems it broke your PR, sorry about that!

**Comment by ShlomoCode** [comment]
fixed

**Comment by ejbills** [comment]
I would recommend just abstracting it out to a ViewModifier, like so:
```swift
import SwiftUI

struct GradientOverlay: ViewModifier {
    var selected: Bool
    
    func body(content: Content) -> some View {
        content.overlay {
            if selected {
                FluidGradient(
                    blobs: [.purple, .blue, .green, .yellow, .red, .purple].shuffled(),
                    highlights: [.red, .orange, .pink, .blue, .purple].shuffled(),
                    speed: 0.45,
                    blur: 0.75
                ).opacity(0.125)
            }
        }
    }
}
```

And then we don't need to redefine the gradient view twice. Instead, we can now just use: 
`.modifier(GradientOverlay(selected: someBoolInput))`

**Comment by ejbills** [comment]
@ShlomoCode I am pending to release the next patch version, I will hold off until you implement what I mentioned so that no one complains about the window radius. Just ping me once finished!
:)

**Comment by ShlomoCode** [comment]
@ejbills I'm stuck here:
```swift
import SwiftUI
import Defaults
import FluidGradient

struct GradientOverlay: ViewModifier {
    var selected: Bool
    var mask: Image?
    
    func body(content: Content) -> some View {
        content.overlay {
            if selected {
                let gradient = FluidGradient(
                    blobs: [.purple, .blue, .green, .yellow, .red, .purple].shuffled(),
                    highlights: [.red, .orange, .pink, .blue, .purple].shuffled(),
                    speed: 0.45,
                    blur: 0.75
                ).opacity(0.125)
                if mask != nil {
                    gradient.mask(mask)
                }
            }
        }
    }
}

struct WindowPreview: View {
    // ....
    private func windowContent(isMinimized: Bool, isHidden: Bool, isSelected: Bool) -> some View {
        Group {
            if isMinimized || isHidden {
                let width = maxWindowDimension.x > 300 ? maxWindowDimension.x : 300
                let labelText = isMinimized ? "Minimized" : "Hidden"
                
                HStack(spacing: 16) {
                    Image(systemName: "eye.slash.fill")
                        .font(.system(size: 20))
                        .foregroundColor(.secondary)
                    
                    Divider()
                    
                    VStack(alignment: .leading) {
                        Text(labelText)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                        
                        TheMarquee(width: width - 100, secsBeforeLooping: 2, speedPtsPerSec: 30, nonMovingAlignment: .leading) {
                            Text(windowInfo.windowName ?? "\(labelText) window")
                                .font(.system(size: 12, weight: .medium))
                                .foregroundStyle(.primary)
                        }
                    }
                }
                .padding(.horizontal, 8)
                .padding()
                .frame(width: width)
                .frame(height: 60)
                .modifier(GradientOverlay(selected: isSelected))
            } else if let cgImage = windowInfo.image {
                let image = Image(decorative: cgImage, scale: 1.0)
                    .resizable()
                    .aspectRatio(contentMode: .fill)
                
                image.modifier(GradientOverlay(selected: isSelected, mask: image))
            }
        }
        .frame(width: isMinimized || isHidden ? nil : calculatedSize.width,
               height: isMinimized || isHidden ? nil : calculatedSize.height,
               alignment: .center)
        .frame(maxWidth: calculatedMaxDimensions?.width, maxHeight: calculatedMaxDimensions?.height)
    }
}
```
I get a strange error `No exact matches in reference to static method 'buildExpression'`

**Comment by ejbills** [comment]
Check latest PR

**Comment by ejbills** [comment]
But, I honestly think I prefer the uniform-clipped windows. Could you maybe make this an option? Something like "use uniform image preview radius".

**Comment by ShlomoCode** [comment]
`useUniformWindowPreviewRadius`

**Comment by ShlomoCode** [comment]
Why not this way? it's shorter and same effect
```
if Defaults[.useUniformWindowPreviewRadius] {
    image.clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
}
image.overlay(isSelected ? fluidGradient().mask(image) : nil)
```

**Pull request merged**
