### PR TITLE
Feat: notify user that the menubar icon can be temporarily show by openning the app

### PR DESCRIPTION
**Pull request by ShlomoCode**
CleanShot 2024-06-30 at 20 13 14@2x

### CODE REVIEW

**Comment by ejbills** [comment]
Hey, thank you. I added in your message and just extended the alert function so it's cleaner. Will be in next version:)

**Comment by ShlomoCode** [comment]
I think people will not pay attention to the information when the title is "Restart required"

In addition, it doesn't seem to me that we need a restart to hide the menubar icon from my testing it works great even without a restart, and only for the presentation you need a restart.

**Comment by ejbills** [comment]
Fixed

**Comment by ShlomoCode** [comment]
It now displays:
CleanShot 2024-06-30 at 20 52 23@2x
But clicking "Cancel" has no effect. Why don't we improve the code so that no restart is needed at all?
I can try to make a PR

**Comment by ShlomoCode** [comment]
Something like that:
```
            Toggle(isOn: $showMenuBarIcon, label: {
                Text("Show Menu Bar Icon")
            })
            .onChange(of: showMenuBarIcon) { _, isOn in
                let delegate = NSApplication.shared.delegate as! AppDelegate
                delegate.updateMenuBarIconStatus()
                
                 if !isOn {
                    MessageUtil.showMessage(
                        title: "Menu Bar Icon Hidden",
                        message: "If you need to access the menu bar icon, launch the app to reveal it for 10 seconds.",
                        completion: { _ in }
                    )
                }
            }
```

**Comment by ShlomoCode** [comment]
https://github.com/ejbills/DockDoor/pull/40

**Pull request closed without merging**
