### PR TITLE
Add French translations on main branch

### PR DESCRIPTION
**Pull request by illavoluntas**
Closed #107 as the localization branch is less advanced.

Some translations will maybe be updated when I will see the final result (the UI). Better translations can come suddenly (as some of the items are hard to translate concisely and precisely).

~~You will also need to add date locale and some missing default labels (in English).
"Checking for updates..." and the screenshot below are the ones I noticed. There are probably more missing.~~
Capture d’écran 2024-07-09 à 13 17 24

### CODE REVIEW

**Comment by ShlomoCode** [comment]
> "Checking for updates..." and the screenshot below are the ones I noticed. There are probably more missing.

It's comming from the [Sparkle](https://github.com/sparkle-project/Sparkle) dependency, so you have to open a PR with them with a translation for the missing strings, and after they release a version with the new translations we can update the dependency and get the translations.

**Comment by ShlomoCode** [comment]
> "Checking for updates..." and the screenshot below are the ones I noticed. There are probably more missing.

It's comming from the [Sparkle](https://github.com/sparkle-project/Sparkle) dependency, so after we merge your translations (which will also enable the French language for the Sparkle dependency) it should be localized automatically.

**Comment by illavoluntas** [comment]
> > "Checking for updates..." and the screenshot below are the ones I noticed. There are probably more missing.
> 
> It's comming from the [Sparkle](https://github.com/sparkle-project/Sparkle) dependency, so after we merge your translations (which will also enable the French language for the Sparkle dependency) it should be localized automatically.

So the date locale will also be adapted automatically?

**Comment by ShlomoCode** [comment]
Yes

**Comment by illavoluntas** [comment]
I do not know why Xcode wants to do things like 8f2a589e9d145447c091dfb892938533c7c635ca. Any idea? This happens automatically when I pull the repository from GitHub to Xcode. It says there are conflicts with Localizable, although there seems to be none...

**Review by ejbills — APPROVED** [review]

**Pull request closed without merging**
