### PR TITLE
feat: open app settings by relaunch

### PR DESCRIPTION
**Pull request by ShlomoCode**
The opening is even if the menu bar icon is enabled, because sometimes many applications are open in the menu bar and there is no way to get to the DockDoor menu, so it seems logical to me that it would always be possible to open DockDoor again to get to the settings.

closes https://github.com/ejbills/DockDoor/issues/57

*************

It is still not perfect, when the user disables "Show Menu Bar Icon" the window loses focus, and may be lost. I try to focus it back but it only brings it back forward and doesn't focus it, so it can get lost in some scenarios. In any case, the user can always simply reopen the app from the Launchpad and the settings window will open and focused again.

https://github.com/user-attachments/assets/c54792b5-653e-4a3d-9086-bcc71093827f

It happens because of this:
```swift
func removeMenuBar() {
        NSApplication.shared.setActivationPolicy(.prohibited) // hide the dock icon
```

If you have a better way to hide the dock icon even when hiding the menus icon, without losing focus, please let me know!

### CODE REVIEW

**Comment by ShlomoCode** [comment]
@hasansultan92 Do you have any thoughts?

**Comment by ejbills** [comment]
Did you look into https://developer.apple.com/documentation/appkit/nsapplication/1428664-presentationoptions?language=objc?

Perhaps something like:
`NSApp.presentationOptions.insert(.autoHideMenuBar)`

But, I am unsure how this behaves.

**Comment by ShlomoCode** [comment]
> Did you look into [developer.apple.com/documentation/appkit/nsapplication/1428664-presentationoptions?language=objc](https://developer.apple.com/documentation/appkit/nsapplication/1428664-presentationoptions?language=objc)?
> 
> Perhaps something like: `NSApp.presentationOptions.insert(.autoHideMenuBar)`
> 

I don't think it's related. From the [options page](https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions):
>Constants that control the presentation of the app, typically for fullscreen apps such as games or kiosks.

The NSApplicationPresentationHideMenuBar option there, for example, refers to hiding the *entire* menu bar.

**Comment by ShlomoCode** [comment]
According to the documentation [`.accessory`](https://developer.apple.com/documentation/appkit/nsapplication/activationpolicy/accessory) should be enough to hide the Dock icon, but in my observation it didn't work. I will try to investigate it again

**Comment by hasansultan92** [comment]
@ShlomoCode my understanding from the issue -and please correct me if I got it wrong- is that people don't want the application take up a whole "window" when opening up the settings, updates, etc. They want to just go to the menu bar and select from the drop down which view they want to go in?

I went through those pieces of documentation that you and @ejbills have sent, yes we should be able to use something like that to tell the system that this application does not need a full fledged "window" unless, infact that is kind of the logic  we will be using most likely in the future when we implement multiple windows in multiple spaces to determine which application has a "window" and which should not have a window to begin with

**Comment by ShlomoCode** [comment]
@hasansultan92 I'm not sure I understand what you mean. The settings window will not be in full screen in any case, the goal is that there will not be a dock icon when the settings are closed.

> infact that is kind of the logic we will be using most likely in the future when we implement multiple windows in multiple spaces to determine which application has a "window" and which should not have a window to begin with

What do you mean?

**Comment by hasansultan92** [comment]
@ShlomoCode it seems like the way an application has something along the lines of an [activationPolicy](https://developer.apple.com/documentation/appkit/nsrunningapplication/1533103-activationpolicy). The applications that form a full fledged window that we interact with fire/emit a .regular event while like you have mentioned above, some applications fire .prohibited.  We are using that information to determine and filter the applications and windows that are "real" and  not

**Comment by ShlomoCode** [comment]
Yes, it's not a bug in the stable version of DockDoor, it's a bug I encountered as soon as I turned off the menu bar icon, the Dock icon immediately popped up

**Comment by ShlomoCode** [comment]
Currently:
- Shows the Dock icon when the Settings window itself is open
- Shows the bar symbol according to the settings
- Not losing focus at all

@ejbills I think it's ready

**Pull request merged**
