### PR TITLE
refactor(defaults): replace numeric enums with named enums; reword keys and variables

### PR DESCRIPTION
**Pull request by ShlomoCode**

### CODE REVIEW

**Comment by ShlomoCode** [comment]
I just think we should adopt a fixed convention about storing options as a number. Does it start with `-1` as in `TitleStyle` or with `0`
What do you think?

**Comment by ejbills** [comment]
Let's keep it consistent with the title options. I would increment everything following never (as 1) up 1. Be sure to set the default value in consts to 2, please!

**Comment by ShlomoCode** [comment]
Yes, I think it should be done in TitleStyle as well :)
It makes sense to me that the selection would be in a consistent order, don't you think so?

**Comment by ejbills** [comment]
Yeah I agree

**Comment by ShlomoCode** [comment]
Should I change `never` to `-1` instead of `0`?

**Comment by ejbills** [comment]
Never: -1
Dimmed on window hover (default) 0

The rest follow suit, be sure to update the consts default key to reflect the changed default key value

**Comment by ShlomoCode** [comment]
@ejbills Redy

**Comment by ShlomoCode** [comment]
@ejbills I'm doing some refactoring in the names of the new settings. Please wait with the next release until I'm done, because then it will be painful to change.

**Comment by ejbills** [comment]
OK just ping me

**Comment by ShlomoCode** [comment]
Still working on it.

**Comment by ejbills** [comment]
All good, take your time. I won't release the next version till you're done.

**Comment by ShlomoCode** [comment]
I will open a new one

**Pull request closed without merging**
