### PR TITLE
refactor: use AXUIElement extension

### PR DESCRIPTION
**Pull request by ShlomoCode**
## Describe your changes
Use `AXUIElement` extension methods (based of https://github.com/lwouis/alt-tab-macos/blob/master/src/api-wrappers/AXUIElement.swift) for shorter and more readable code

The `AXUIElement` extension it's just a **thin** wrapper over the macOS AX APIs, which saves the call success check and dealing with the `inout` variable and types, etc.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If this change affects core functionality, I have added a description highlighting the changes
- [x] I have followed conventional commit guidelines

## Core Functionality Changes

There shouldn't be any functional change

### CODE REVIEW

**Comment by ShlomoCode** [comment]
I'm not handling `DockObserver.swift` here as I'm going to rewrite the whole thing into the more efficient way from PR #214.

**Comment by ShlomoCode** [comment]
I'm not handling `DockObserver.swift` here as I'm going to rewrite the whole thing into the more efficient way from PR #214.

**Comment by ejbills** [comment]
Good to merge?

**Comment by ShlomoCode** [comment]
Yes it's ready to merge. Do you like the changes?

**Comment by ShlomoCode** [comment]
@ejbills Yes it's ready to merge. Do you like the changes?

**Review by ejbills — APPROVED** [review]

**Comment by ejbills** [comment]
> @ejbills Yes it's ready to merge. Do you like the changes?

Yes! Reduces our repeated AXUIElement code blocks. Nice addition.

**Pull request merged**
